apiVersion: v1
kind: Service
metadata:
  labels:
    name: jab
  name: jab
spec:
  type: NodePort
  ports:
    # The port that this service should serve on.
    - nodePort: 31333
      targetPort: 80
      protocol: TCP
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    name: jab